project_id = "tqtaerijrqfkwxennxae"

[functions.generate-summary]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = true

[functions.import-google-books]
verify_jwt = true

[functions.catalog-search]
verify_jwt = false

[functions.sitemap]
verify_jwt = false